import { defaultEffects, defaultVisual, type Sequence, type Track } from "../types";
import { emptyDoc, loadScript, saveScript, type ScriptDoc } from "./script";
import { local } from "./store";

/**
 * The material the tutorial runs on. A board with nothing on it cannot teach anything: the lessons
 * that used to fire on a first visit pointed at buttons that only exist once there is media to act
 * on, which is why they pointed at nothing at all.
 *
 * **It never reaches anybody's account.** `write()` in `store.ts` only sends rows whose id is a UUID
 * (`tracks.filter(track => isUuid(track.id))`), and every id here is prefixed `demo:` instead. So the
 * demo cannot be uploaded, cannot be synced to another device, and cannot survive teardown in the
 * cloud, because it was never there. That prefix is also the whole teardown contract: anything the
 * user makes carries a real UUID, so `clearDemo` cannot reach their work even in principle.
 *
 * Files come from `public/demo/`, generated by `scripts/demo-assets.mjs`. Nothing is fetched.
 */

export const DEMO_PREFIX = "demo:";
export const isDemo = (id: string) => id.startsWith(DEMO_PREFIX);

/** The demo script's name, which is how teardown recognises its own script and not yours. */
const SCRIPT_NAME = "A Winter's Tale (demo)";

const asset = (file: string) => `${import.meta.env.BASE_URL}demo/${file}`;

const track = (id: string, title: string, file: string, kind: Track["kind"], caption = ""): Track => ({
  id: DEMO_PREFIX + id,
  title,
  url: asset(file),
  kind,
  effects: defaultEffects(),
  createdAt: new Date().toISOString(),
  ...(kind === "audio" ? {} : { visual: { ...defaultVisual(), caption } }),
});

/** Three sounds, two stills, a clip and a deck. Enough to build a cue list out of, and no more. */
export const demoTracks = (): Track[] => [
  track("door", "Door slam", "door-slam.mp3", "audio"),
  track("thunder", "Thunder roll", "thunder-roll.mp3", "audio"),
  track("applause", "Applause", "applause.mp3", "audio"),
  track("act-one", "Act One title", "act-one.jpg", "image", "Act One, Scene i"),
  track("curtain", "Curtain", "curtain.jpg", "image", "House to half"),
  track("house", "House lights", "house-lights.mp4", "video"),
  track("deck", "Programme deck", "deck.html", "embed"),
];

/**
 * A short script with two cue words in it, so the reader has something to flash on. `lookahead` is
 * left at the default: this is a demonstration of the mechanism, not a tuned setup.
 */
export const demoScript = (): ScriptDoc => ({
  ...emptyDoc(),
  name: SCRIPT_NAME,
  html: [
    "<h3>Act One, Scene i</h3>",
    "<p class='script-character'>HERMIONE</p>",
    "<p class='script-dialogue'>You will stay a little longer. The court is dull without you.</p>",
    "<p class='script-parenthetical'>(A door slams offstage.)</p>",
    "<p class='script-character'>LEONTES</p>",
    "<p class='script-dialogue'>Too hot, too hot. I have tremor cordis on me.</p>",
    "<p class='script-parenthetical'>(Thunder, and the lights go to half.)</p>",
    "<p class='script-dialogue'>Go on then. The winter is not done with us.</p>",
  ].join(""),
  cues: [
    { id: DEMO_PREFIX + "cue-door", words: "door slams", message: "Stand by, door slam" },
    { id: DEMO_PREFIX + "cue-thunder", words: "thunder", message: "Stand by, thunder and lights to half" },
  ],
});

/**
 * Put the demo material on the board. Idempotent: running it twice does not double the library, so
 * replaying the tutorial is safe.
 *
 * The demo goes in the personal workspace only, never into a named project, so it cannot land in the
 * middle of a production somebody is actually working on.
 */
export function loadDemo() {
  const mine = local.get<Track[]>("tracks", []).filter(t => !isDemo(t.id));
  local.set("tracks", [...demoTracks(), ...mine]);
  // Only if there is no script already. Someone replaying the tutorial three weeks in has a real
  // script loaded, and overwriting it to teach them about scripts would be its own punchline.
  if (!loadScript().html) saveScript(demoScript());
}

/**
 * Take it all back off. Anything the user built on top of the demo stays: their own tracks are
 * untouched, and a sequence they made keeps every cue except the ones pointing at demo media, which
 * would otherwise be cues that play nothing.
 */
export function clearDemo() {
  local.set("tracks", local.get<Track[]>("tracks", []).filter(t => !isDemo(t.id)));
  local.set("sequences", local.get<Sequence[]>("sequences", [])
    .filter(s => !isDemo(s.id))
    .map(s => ({ ...s, items: s.items.filter(i => !isDemo(i.trackId)) })));
  if (loadScript().name === SCRIPT_NAME) saveScript(emptyDoc());
}

/** Whether any of it is currently on the board, which is what the teardown offer keys off. */
export const demoPresent = () => local.get<Track[]>("tracks", []).some(t => isDemo(t.id));
