import { newCode } from "./projects";
import { deleteShowBundle, listShowBundles, loadShowBundle, nativeStore, saveShowBundle } from "./nativeStore";
import { local } from "./store";
import { PERMS, ROLE_PRESETS, type MemberStatus, type Perm, type Role, type Show, type Ticket } from "./shows";

/**
 * A show whose only authority is this browser's storage.
 *
 * The door was Postgres and nothing else: `joinShow` calls the `join_show` RPC and `refreshTicket`
 * calls `show_state`, both through a helper that throws "Cloud is not configured for this build."
 * The native build now carries a Bluetooth and Wi-Fi mesh, so the phones in a venue with no
 * internet can hear each other perfectly well; what none of them could do was get in, because the
 * one thing that could answer the door was a database nobody in the building could reach.
 *
 * So the host's device is the authority instead. It mints the show, holds the roster, and answers
 * over the wire with the `door` message it already sends. A joiner mints its own ticket and that
 * ticket is worth nothing until the host answers: `perms` is written here only by `admitLocally`,
 * which is the same withholding `0003_the_door_is_real.sql` does in SQL.
 */

/**
 * The show id IS the code that gets read out. Not a uuid with a code beside it.
 *
 * Offline there is nobody handing out uuids, so a second identifier would only be a second thing to
 * keep in step with the first. One string does both jobs, and it is generated by `newCode`, whose
 * alphabet has no O/0 and no I/1/L in it, because this gets read aloud across a dark theatre.
 */
export const LOCAL_SHOW_PREFIX = "CF-";
const LOCAL_ID = /^CF-[A-Z0-9]{6}$/;
/** Case-insensitive and trimmed: a key read aloud gets typed back in whatever case is to hand. */
export const isLocalShowId = (id: string) => LOCAL_ID.test(id.trim().toUpperCase());

const SHOWS = "localShows";
const SEATS = "localSeats";
const rolesKey = (showId: string) => `localRoles:${showId}`;

/**
 * One device at this show, as the host's device remembers it.
 *
 * `state` is the door's vocabulary rather than the database's, because the host answers with a
 * `door` message and this is what it last said. `Ticket.status` is the other spelling of the same
 * fact, and `statusOf` is the translation between them.
 */
type Seat = { member: string; show: string; name: string; role: string | null; perms: Perm[]; host: boolean; state: "waiting" | "in" | "out" };

const seats = () => local.get<Seat[]>(SEATS, []);
const saveSeats = (next: Seat[]) => local.set(SEATS, next);

export const listLocalShows = (): Show[] => local.get<Show[]>(SHOWS, []);

export function saveLocalShow(show: Show) {
  const all = listLocalShows();
  const at = all.findIndex(s => s.id === show.id);
  // Newest first, which is the order the cloud list comes back in, and an edit stays where it was.
  local.set(SHOWS, at < 0 ? [show, ...all] : all.map((s, i) => (i === at ? show : s)));
  toDisk(show.id);
}

/**
 * A copy of the show on the app's own disk, on top of the one in local storage.
 *
 * Local storage is a WebView's, and a WebView's can be cleared: by the operating system reclaiming
 * space, by a "clear data" press in Android's app settings, by a reinstall the week before a run.
 * That is an acceptable way to lose a browser tab and not an acceptable way to lose the show a
 * company has been rehearsing, so on the native build it is written twice and read back from disk
 * when local storage comes up empty.
 *
 * Fire and forget. A disk that will not take the copy must not stop the show being saved in the
 * place the app actually reads it from.
 */
function toDisk(id: string) {
  if (!nativeStore()) return;
  const show = listLocalShows().find(s => s.id === id);
  if (!show) return;
  void saveShowBundle(id, { v: 1, show, roles: localRoles(id) })
    .catch(error => console.warn("[show] the copy on this device was not written", error));
}

type Bundle = { v: 1; show: Show; roles: Role[] };

/**
 * Put back what the disk still has, when local storage has nothing.
 *
 * Guarded on empty rather than merged, and that guard is the whole safety of this. A merge would
 * have to decide which copy of a show is the real one, and getting that wrong the morning after a
 * rehearsal silently reverts the changes somebody made in it. Nothing to lose is the only case
 * where restoring cannot lose anything.
 */
export async function restoreShowsFromDisk(): Promise<number> {
  if (!nativeStore() || listLocalShows().length) return 0;
  let restored = 0;
  for (const id of await listShowBundles()) {
    const bundle = await loadShowBundle<Bundle>(id);
    if (!bundle?.show) continue;
    const all = listLocalShows();
    local.set(SHOWS, [...all, bundle.show]);
    setLocalRoles(id, bundle.roles ?? []);
    restored++;
  }
  return restored;
}

export const localRoles = (showId: string): Role[] => local.get<Role[]>(rolesKey(showId), []);
export const setLocalRoles = (showId: string, roles: Role[]) => {
  local.set(rolesKey(showId), roles);
  // The jobs and their keys are half of what a show is. A disk copy carrying the show and not the
  // keys people type to get into it would restore something nobody can join.
  toDisk(showId);
};

/**
 * Every key on this device -- every show id and every job's code -- is one namespace, because the
 * door takes one box and has to work out what you meant by what you typed. The database enforces
 * that with a unique index; here the list is short enough to simply look at.
 */
const takenKeys = () => new Set(listLocalShows().flatMap(show => [
  show.id.toUpperCase(),
  (show.password ?? "").toUpperCase(),
  ...localRoles(show.id).map(role => (role.code ?? "").toUpperCase()),
]));

const freeKey = (used: Set<string>) => {
  for (let n = 0; n < 8; n++) {
    const key = newCode();
    if (!used.has(key)) { used.add(key); return key; }
  }
  throw new Error("Could not find a free key. Try again.");
};

export function newLocalShow(name: string, sequenceId: string | null): Show {
  const used = takenKeys();
  const id = LOCAL_SHOW_PREFIX + freeKey(used);
  // The password is the id. There is one string to read out, and `joinLocalShow` takes it either
  // way, so a host who reads out the id has not read out something that turns out not to work.
  const show: Show = { id, name: name.trim() || "Untitled show", password: id, sequenceId, startedAt: null, owner: null };
  saveLocalShow(show);
  // The three jobs almost every show has, with fresh codes, so an offline show is usable the moment
  // it exists: there is no other screen to go and set it up on, and no account to set it up under.
  setLocalRoles(id, ROLE_PRESETS.map(preset => ({ id: crypto.randomUUID(), name: preset.name, perms: preset.perms, code: freeKey(used) })));
  return show;
}

export function updateLocalShow(id: string, patch: { name?: string; password?: string | null; sequence_id?: string | null; started_at?: string | null }) {
  const show = listLocalShows().find(s => s.id === id);
  if (!show) throw new Error("That show is already gone.");
  // The patch arrives in the shape the table takes, so the two spellings are reconciled here rather
  // than in every caller.
  saveLocalShow({
    ...show,
    ...(patch.name !== undefined ? { name: patch.name } : {}),
    ...(patch.password !== undefined ? { password: patch.password } : {}),
    ...(patch.sequence_id !== undefined ? { sequenceId: patch.sequence_id } : {}),
    ...(patch.started_at !== undefined ? { startedAt: patch.started_at } : {}),
  });
}

export function deleteLocalShow(id: string) {
  local.set(SHOWS, listLocalShows().filter(show => show.id !== id));
  // Including the copy on disk, or the next start would restore a show somebody deleted.
  if (nativeStore()) void deleteShowBundle(id).catch(() => undefined);
  // The jobs and the roster are part of the show. Leaving them behind would keep a deleted show's
  // codes answering the door, and leave member ids pointing at a room that is not there any more.
  setLocalRoles(id, []);
  saveSeats(seats().filter(seat => seat.show !== id));
}

/** A role id says nothing about which show holds it, so the show is the one that has it. */
const showOfRole = (roleId: string) => listLocalShows().find(show => localRoles(show.id).some(role => role.id === roleId)) ?? null;

/**
 * Whether a job belongs to a show this device is running on its own.
 *
 * A local role's id is a uuid, exactly like a row's, so the id cannot answer this by its shape the
 * way a show's can. Asking which show holds it is the only honest test, and the list is short.
 */
export const isLocalRole = (roleId: string) => !!showOfRole(roleId);

export function addLocalRole(showId: string, name: string, perms: Perm[]): Role {
  const role: Role = { id: crypto.randomUUID(), name: name.trim() || "Crew", perms, code: freeKey(takenKeys()) };
  setLocalRoles(showId, [...localRoles(showId), role]);
  return role;
}

export function updateLocalRole(id: string, patch: { name?: string; perms?: Perm[]; code?: string }) {
  const show = showOfRole(id);
  if (!show) throw new Error("That job is already gone.");
  const roles = localRoles(show.id);
  // The same refusal the database gives, for the same reason: two jobs sharing a code is a door
  // that cannot say which of them you meant.
  const mine = roles.find(role => role.id === id);
  if (patch.code && patch.code.toUpperCase() !== (mine?.code ?? "").toUpperCase() && takenKeys().has(patch.code.toUpperCase())) {
    throw new Error("Another job is already using that key.");
  }
  setLocalRoles(show.id, roles.map(role => (role.id === id ? { ...role, ...patch } : role)));
}

export function deleteLocalRole(id: string) {
  const show = showOfRole(id);
  if (!show) return;
  setLocalRoles(show.id, localRoles(show.id).filter(role => role.id !== id));
}

/** The two spellings of one fact: what the host last said at the door, and what a ticket calls it. */
const statusOf = (state: Seat["state"]): MemberStatus => state === "in" ? "admitted" : state === "out" ? "denied" : "waiting";

const ticketFor = (seat: Seat, show: Show): Ticket => ({
  member: seat.member,
  show: show.id,
  // The show's name, not the person's. That is what the RPC puts in this field and what the crew
  // screen prints as its heading; the person's name is the roster's business.
  name: show.name,
  sequence: show.sequenceId,
  started: show.startedAt,
  role: seat.role,
  // Someone still at the door, or turned away from it, holds no permissions at all, whatever is
  // written on their seat. The same line `join_show` takes: they hold a ticket, not a job.
  perms: seat.state === "in" ? seat.perms : [],
  host: seat.host,
  status: statusOf(seat.state),
});

/** Whether the door should answer this key here rather than asking a database about it. */
export const isLocalKey = (key: string) => {
  const typed = key.trim();
  if (!typed) return false;
  if (isLocalShowId(typed)) return true;
  const upper = typed.toUpperCase();
  return listLocalShows().some(show =>
    (show.password ?? "").toUpperCase() === upper || localRoles(show.id).some(role => (role.code ?? "").toUpperCase() === upper));
};

/**
 * One box, offline. A job's code puts you in that job and leaves you waiting; the show's own code
 * puts you in as a collaborator with everything, because whoever holds it is running the show.
 *
 * A host who cannot get into their own show cannot admit anybody, which is a deadlock with no way
 * out of it five minutes before curtain, so they never wait.
 */
export function joinLocalShow(key: string, name: string): Ticket {
  const typed = key.trim().toUpperCase();
  const shows = listLocalShows();
  const asHost = shows.find(show => (show.password ?? "").toUpperCase() === typed || show.id.toUpperCase() === typed) ?? null;
  const job = asHost ? null : shows
    .flatMap(show => localRoles(show.id).map(role => ({ show, role })))
    .find(({ role }) => (role.code ?? "").toUpperCase() === typed) ?? null;
  const show = asHost ?? job?.show ?? null;
  // The wording the RPC uses. The person has typed one thing into one box, and the honest answer is
  // that nothing here goes by it, not which of the two kinds of key it failed to be.
  if (!show) throw new Error("Nothing here goes by that key.");

  const role = job ? job.role.name : "Collaborator";
  const held = seats();
  // Typing the same key again on the same device is the same person coming back, not a second one.
  // Minting a fresh seat every time grew the list without bound on a host that reopens its own show
  // on every reload, and it put a crew member who refreshed at the back of a queue they were
  // already in, under a member id the host had never seen.
  const existing = held.find(seat => seat.show === show.id && seat.host === !!asHost && seat.role === role && seat.name === name.trim());
  const seat: Seat = existing ?? {
    member: crypto.randomUUID(),
    show: show.id,
    name: name.trim(),
    role,
    // A joiner writes its own seat, so it must not be able to write itself any powers. The perms
    // arrive when the host answers the door, and not one moment before.
    perms: asHost ? PERMS.map(perm => perm.key) : [],
    host: !!asHost,
    state: asHost ? "in" : "waiting",
  };
  if (!existing) saveSeats([...held, seat]);
  return ticketFor(seat, show);
}

/**
 * Write down what the door said, on whichever device heard it.
 *
 * Both ends need this and for different reasons. The joiner needs it because the `door` message is
 * the only place its permissions ever existed: without writing them down, a reload re-reads a seat
 * that still says waiting and throws away a job the host granted an hour ago. The host needs it
 * because offline `memberPerms` has no database to ask, so the seat it writes when it admits
 * somebody is the only record of what that device is allowed to do on its next message.
 *
 * An upsert, not an update. The host has no seat for a crew member at all until it admits them: the
 * joiner minted that seat in its own storage, which the host cannot see.
 */
export function rememberDoor(
  member: string,
  show: string,
  state: Seat["state"],
  role: string | null,
  perms: Perm[],
  name = "",
): Ticket | null {
  const all = seats();
  const held = all.find(seat => seat.member === member);
  const next: Seat = {
    member,
    show,
    name: name.trim() || held?.name || "",
    role,
    // Turned away or still waiting means no permissions, whatever the message carried. The same
    // line `show_state` takes in SQL, kept here so the two doors cannot disagree.
    perms: state === "in" ? perms : [],
    host: held?.host ?? false,
    state,
  };
  saveSeats(held ? all.map(seat => (seat.member === member ? next : seat)) : [...all, next]);
  return localTicket(member);
}

/** What `refreshTicket` falls back to: the seat this device was given, read back. */
export function localTicket(member: string): Ticket | null {
  const seat = seats().find(s => s.member === member);
  if (!seat) return null;
  const show = listLocalShows().find(s => s.id === seat.show);
  // A seat whose show has been deleted is not a ticket. Handing back half of one would leave a crew
  // screen sitting in a room that no longer exists, waiting for a host that will never answer.
  return show ? ticketFor(seat, show) : null;
}

/**
 * What this device is allowed to do here, offline.
 *
 * The mirror of `memberPerms`: the seat is the authority, a seat belonging to another show is a
 * stranger to this one, and the person holding the show's own key holds everything.
 */
export function localPerms(member: string, showId: string): Perm[] {
  const ticket = localTicket(member);
  if (!ticket || ticket.show !== showId) return [];
  return ticket.host ? PERMS.map(perm => perm.key) : (ticket.perms ?? []);
}

export function localRoster(showId: string) {
  return seats().filter(seat => seat.show === showId)
    .map(({ member, name, role, perms, state }) => ({ member, name, role, perms, state }));
}
