import { createClient } from "@supabase/supabase-js";
import type { Sequence, SequenceItem, Track } from "../types";
const url = import.meta.env.VITE_SUPABASE_URL, key = import.meta.env.VITE_SUPABASE_ANON_KEY;
export const supabase = url && key ? createClient(url, key) : null;

// Auth: email + password. Cloud save/hydrate already gate on getUser(), so signing in activates them.
export async function signUp(email: string, password: string) { if (!supabase) throw new Error("Cloud not configured"); const { error } = await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${location.origin}/studio` } }); if (error) throw error; }
// NOTE: emailRedirectTo only works if the URL is allow-listed in Supabase → Authentication → URL
// Configuration. Otherwise Supabase falls back to Site URL, which defaults to http://localhost:3000.
export async function signIn(email: string, password: string) { if (!supabase) throw new Error("Cloud not configured"); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; }
export async function signOut() { await supabase?.auth.signOut(); }
export function onAuth(cb: (email: string | null) => void) { if (!supabase) { cb(null); return () => {}; } supabase.auth.getUser().then(({ data }) => cb(data.user?.email ?? null)); const { data } = supabase.auth.onAuthStateChange((_e, session) => cb(session?.user?.email ?? null)); return () => data.subscription.unsubscribe(); }
export const local = { get<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(`cueflow:${key}`) || "") as T; } catch { return fallback; } }, set(key: string, value: unknown) { localStorage.setItem(`cueflow:${key}`, JSON.stringify(value)); } };
// Session-free upload: anon key writes to the public/ prefix (RLS policy allows it), bucket is public-read.
export async function uploadTrack(file: File) { if (!supabase) return URL.createObjectURL(file); const path = `public/${crypto.randomUUID()}-${file.name}`; const { error } = await supabase.storage.from("audio").upload(path, file, { contentType: file.type || "audio/mpeg", upsert: false }); if (error) throw error; return supabase.storage.from("audio").getPublicUrl(path).data.publicUrl; }
const isUuid = (id: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);
export async function persist(tracks: Track[], sequences: Sequence[]) { local.set("tracks", tracks); local.set("sequences", sequences); if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const cloudTracks = tracks.filter(track => isUuid(track.id)); await supabase.from("tracks").upsert(cloudTracks.map(track => ({ id: track.id, user_id: user.id, title: track.title, source_url: track.url, effects: track.effects }))); const cloudSequences = sequences.filter(sequence => isUuid(sequence.id) && sequence.items.every(item => isUuid(item.trackId))); await supabase.from("sequences").upsert(cloudSequences.map(sequence => ({ id: sequence.id, user_id: user.id, name: sequence.name }))); for (const sequence of cloudSequences) { await supabase.from("sequence_items").delete().eq("sequence_id", sequence.id); if (sequence.items.length) await supabase.from("sequence_items").insert(sequence.items.map((item, position) => ({ id: item.id, sequence_id: sequence.id, track_id: item.trackId, position, label: item.label, effects: item.effects }))); }
}
export async function hydrateCloud() { if (!supabase) return null; const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const { data: tracks } = await supabase.from("tracks").select("id,title,source_url,effects,created_at").eq("user_id", user.id); const { data: sequences } = await supabase.from("sequences").select("id,name,created_at").eq("user_id", user.id); if (!tracks || !sequences) return null; const ids = sequences.map(sequence => sequence.id); const { data: items } = ids.length ? await supabase.from("sequence_items").select("id,sequence_id,track_id,label,effects,position").in("sequence_id", ids).order("position") : { data: [] }; return { tracks: tracks.map(row => ({ id: row.id, title: row.title, url: row.source_url, effects: row.effects, createdAt: row.created_at } as Track)), sequences: sequences.map(sequence => ({ id: sequence.id, name: sequence.name, createdAt: sequence.created_at, items: (items ?? []).filter(item => item.sequence_id === sequence.id).map(item => ({ id: item.id, trackId: item.track_id, label: item.label, effects: item.effects } as SequenceItem)) } as Sequence)) };
}
