import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { FastForward, Download, ListMusic, Pause, Play, Plus, Rewind, RotateCcw, SlidersHorizontal, Upload, Volume2 } from "lucide-react";
import { AudioEngine, makeReversedFile } from "./lib/audio";
import { clueLessSequence, initialTracks } from "./lib/cues";
import { hydrateCloud, local, persist, uploadTrack } from "./lib/store";
import { cloneEffects, defaultEffects, Effects, Sequence, SequenceItem, Track } from "./types";

const format = (seconds = 0) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`;
const controls: { key: keyof Effects; label: string; min: number; max: number; step: number; unit?: string }[] = [
  { key: "speed", label: "Speed", min: .5, max: 2, step: .05, unit: "x" }, { key: "volume", label: "Volume", min: 0, max: 1, step: .01 }, { key: "gain", label: "Gain", min: .1, max: 2, step: .05, unit: "x" }, { key: "reverb", label: "Reverb", min: 0, max: 1, step: .05 }, { key: "fadeIn", label: "Fade in", min: 0, max: 8, step: .25, unit: "s" }, { key: "fadeOut", label: "Fade out", min: 0, max: 8, step: .25, unit: "s" }, { key: "distortion", label: "Distortion", min: 0, max: 1, step: .05 }
];

// ponytail: pure-black window — put it on the mirrored display so the audience sees nothing of the app.
function Audience() { return <main className="min-h-screen bg-black" />; }

export default function App() {
  const audio = useRef<HTMLAudioElement>(new Audio()); const engine = useRef(new AudioEngine());
  const [tracks, setTracks] = useState<Track[]>(() => local.get("tracks", initialTracks()));
  const [sequences, setSequences] = useState<Sequence[]>(() => local.get("sequences", []));
  const [selectedId, setSelectedId] = useState(() => local.get("tracks", initialTracks())[0]?.id ?? "");
  const [sequenceId, setSequenceId] = useState<string>(() => local.get<Sequence[]>("sequences", [])[0]?.id ?? "");
  const [cueIndex, setCueIndex] = useState(0); const [playing, setPlaying] = useState(false); const [time, setTime] = useState(0); const [tab, setTab] = useState<"library" | "editor" | "sequence">("library"); const [myInstants, setMyInstants] = useState("");
  const selected = tracks.find(t => t.id === selectedId) ?? tracks[0]; const selectedSequence = sequences.find(s => s.id === sequenceId);
  useEffect(() => { void persist(tracks, sequences); }, [tracks, sequences]);
  useEffect(() => { void hydrateCloud().then(cloud => { if (!cloud) return; setTracks(old => [...old, ...cloud.tracks.filter(track => !old.some(existing => existing.id === track.id))]); setSequences(old => [...old, ...cloud.sequences.filter(sequence => !old.some(existing => existing.id === sequence.id))]); }); }, []);
  useEffect(() => { const a = audio.current; a.crossOrigin = "anonymous"; const tick = () => { setTime(a.currentTime); const fade = selected?.effects.fadeOut ?? 0; if (fade && Number.isFinite(a.duration) && a.duration - a.currentTime <= fade) a.volume = Math.max(0, selected!.effects.volume * (a.duration - a.currentTime) / fade); }; const ended = () => setPlaying(false); a.addEventListener("timeupdate", tick); a.addEventListener("ended", ended); return () => { a.pause(); a.removeEventListener("timeupdate", tick); a.removeEventListener("ended", ended); }; }, [selected]);
  useEffect(() => { const keys = (e: KeyboardEvent) => { if (!selectedSequence || (e.target as HTMLElement).tagName === "INPUT") return; if (e.key === "ArrowRight") { e.preventDefault(); playCue(Math.min(cueIndex + 1, selectedSequence.items.length - 1)); } if (e.key === "ArrowLeft") { e.preventDefault(); playCue(Math.max(cueIndex - 1, 0)); } }; window.addEventListener("keydown", keys); return () => window.removeEventListener("keydown", keys); });
  const updateEffects = (effects: Effects) => { if (!selected) return; setTracks(all => all.map(t => t.id === selected.id ? { ...t, effects } : t)); engine.current.apply(audio.current, effects); };
  const play = async (track = selected, fx = selected?.effects) => { if (!track || !fx) return; if (audio.current.src !== new URL(track.url, window.location.href).href) { audio.current.src = track.url; audio.current.currentTime = 0; } await engine.current.play(audio.current, fx); setPlaying(true); };
  const toggle = () => playing ? (audio.current.pause(), setPlaying(false)) : play();
  const playCue = (index: number) => { if (!selectedSequence) return; const item = selectedSequence.items[index]; const track = tracks.find(t => t.id === item.trackId); setCueIndex(index); if (track) play(track, item.effects); };
  const addFiles = async (event: ChangeEvent<HTMLInputElement>) => { const files = [...(event.target.files ?? [])]; const created = await Promise.all(files.filter(f => f.type.startsWith("audio/")).map(async file => ({ id: crypto.randomUUID(), title: file.name.replace(/\.[^.]+$/, ""), url: await uploadTrack(file), effects: defaultEffects(), createdAt: new Date().toISOString() }))); if (created.length) { setTracks(old => [...old, ...created]); setSelectedId(created[0].id); } };
  const createScriptSequence = () => { const sequence = clueLessSequence(tracks); setSequences(old => [...old, sequence]); setSequenceId(sequence.id); setCueIndex(0); setTab("sequence"); };
  const addToSequence = () => { if (!selected) return; let id = sequenceId; if (!id) { const sequence: Sequence = { id: crypto.randomUUID(), name: "Untitled sequence", items: [], createdAt: new Date().toISOString() }; setSequences(old => [...old, sequence]); id = sequence.id; setSequenceId(id); } setSequences(old => old.map(s => s.id !== id ? s : { ...s, items: [...s.items, { id: crypto.randomUUID(), trackId: selected.id, label: selected.title, effects: cloneEffects(selected.effects) }] })); };
  const importMyInstants = () => { if (!myInstants.trim()) return; const title = myInstants.split("/").filter(Boolean).pop()?.replace(/[-_]/g, " ") || "Myinstants sound"; const track: Track = { id: crypto.randomUUID(), title, url: myInstants.trim(), effects: defaultEffects(), createdAt: new Date().toISOString() }; setTracks(old => [...old, track]); setSelectedId(track.id); setMyInstants(""); };
  const bakeReverse = async () => { if (!selected) return; const file = await makeReversedFile(selected.url, selected.title); const track: Track = { id: crypto.randomUUID(), title: `${selected.title} (reversed)`, url: await uploadTrack(file), effects: { ...selected.effects, reverse: false }, createdAt: new Date().toISOString() }; setTracks(old => [...old, track]); setSelectedId(track.id); };
  const nav = [{ id: "library", icon: Volume2, label: "Library" }, { id: "editor", icon: SlidersHorizontal, label: "Editor" }, { id: "sequence", icon: ListMusic, label: "Sequences" }] as const;
  if (location.hash === "#/audience") return <Audience />;
  return <main className="min-h-screen text-slate-100"><WebglBackdrop /><div className="relative mx-auto min-h-screen max-w-7xl px-5 py-6 lg:px-9"><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.35em] text-cyan-300">Live audio cue system</p><h1 className="text-3xl font-black tracking-tight">CueFlow</h1></div><button onClick={() => window.open(`${location.href.split("#")[0]}#/audience`, "cueflow-audience", "popup,width=1000,height=600")} className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold hover:bg-white/20">Open audience display</button></header>
  <section className="mt-7 grid gap-6 lg:grid-cols-[220px_1fr]"><nav className="glass rounded-3xl p-3"><div className="space-y-1">{nav.map(({ id, icon: Icon, label }) => <button key={id} onClick={() => setTab(id)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-bold ${tab === id ? "bg-cyan-400 text-slate-950" : "text-slate-300 hover:bg-white/10"}`}><Icon size={18}/>{label}</button>)}</div><div className="mt-7 rounded-2xl bg-slate-950/45 p-4 text-xs leading-5 text-slate-300"><b className="text-white">Presenter mode</b><br/>Put the audience window on the mirrored display. It shows only the active cue; controls stay here.</div></nav>
  <section className="glass rounded-3xl p-5 md:p-7">{tab === "library" && <Library tracks={tracks} selectedId={selectedId} select={setSelectedId} addFiles={addFiles} addToSequence={addToSequence} myInstants={myInstants} setMyInstants={setMyInstants} importMyInstants={importMyInstants}/>} {tab === "editor" && selected && <Editor track={selected} update={updateEffects} bakeReverse={bakeReverse}/>} {tab === "sequence" && <Sequences sequences={sequences} selectedId={sequenceId} select={setSequenceId} createScriptSequence={createScriptSequence} addToSequence={addToSequence} tracks={tracks} playCue={playCue} cueIndex={cueIndex}/>}</section></section>
  {selected && <Player track={selected} playing={playing} toggle={toggle} time={time} seek={(value: number) => { audio.current.currentTime = value; setTime(value); }} jump={(seconds: number) => audio.current.currentTime = Math.max(0, audio.current.currentTime + seconds)} effects={selected.effects} update={updateEffects}/>}</div></main>;
}
function Library({ tracks, selectedId, select, addFiles, addToSequence, myInstants, setMyInstants, importMyInstants }: any) { return <><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Cloud library</p><h2 className="section-title">Your soundboard</h2></div><label className="button"><Upload size={17}/> Upload audio<input className="hidden" type="file" accept="audio/*" multiple onChange={addFiles}/></label></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{tracks.map((track: Track) => <button onClick={() => select(track.id)} key={track.id} className={`rounded-2xl border p-4 text-left transition ${selectedId === track.id ? "border-cyan-300 bg-cyan-300/10" : "border-white/10 bg-slate-950/25 hover:bg-white/10"}`}><p className="font-bold capitalize">{track.title}</p><p className="mt-1 text-xs text-slate-400">{track.effects.speed}x • {Math.round(track.effects.volume * 100)}% volume</p></button>)}</div><div className="mt-6 flex flex-wrap gap-3"><button onClick={addToSequence} className="button secondary"><Plus size={17}/> Add selected to sequence</button><a className="button secondary" href="https://www.myinstants.com" target="_blank">Browse Myinstants</a><input className="field flex-1" value={myInstants} onChange={e => setMyInstants(e.target.value)} placeholder="Paste a direct Myinstants audio URL"/><button onClick={importMyInstants} className="button secondary">Import URL</button></div></> }
function Editor({ track, update, bakeReverse }: { track: Track; update: (fx: Effects) => void; bakeReverse: () => Promise<void> }) { return <><p className="eyebrow">Non-destructive editor</p><h2 className="section-title">{track.title}</h2><p className="mt-2 max-w-2xl text-sm text-slate-400">Edits are saved with this sound and also apply immediately in playback and sequences. Reverse can be rendered as a new cloud-backed WAV version.</p><EffectControls effects={track.effects} update={update}/><label className="mt-6 flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/30 p-4 text-sm font-bold"><input type="checkbox" checked={track.effects.reverse} onChange={e => update({ ...track.effects, reverse: e.target.checked })}/> Mark for reverse render</label>{track.effects.reverse && <button onClick={() => void bakeReverse()} className="button mt-4"><RotateCcw size={17}/> Render & save reversed version</button>}</> }
function Sequences({ sequences, selectedId, select, createScriptSequence, addToSequence, tracks, playCue, cueIndex }: any) { const sequence = sequences.find((s: Sequence) => s.id === selectedId); return <><div className="flex items-center justify-between"><div><p className="eyebrow">Manual cue deck</p><h2 className="section-title">Sequences</h2></div><button onClick={createScriptSequence} className="button"><Download size={17}/> Build Clue-less sequence</button></div><div className="mt-5 flex flex-wrap gap-2">{sequences.map((s: Sequence) => <button onClick={() => select(s.id)} className={`rounded-full px-4 py-2 text-sm font-bold ${s.id === selectedId ? "bg-cyan-300 text-slate-950" : "bg-white/10"}`} key={s.id}>{s.name}</button>)}<button onClick={addToSequence} className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold"><Plus size={16} className="inline"/> New/append</button></div>{sequence ? <ol className="mt-6 space-y-2">{sequence.items.map((item: SequenceItem, index: number) => <li key={item.id}><button onClick={() => playCue(index)} className={`flex w-full items-center justify-between rounded-xl border px-4 py-3 text-left ${index === cueIndex ? "border-cyan-300 bg-cyan-300/10" : "border-white/10 bg-slate-950/25"}`}><span><b className="mr-3 text-cyan-300">{String(index + 1).padStart(2, "0")}</b>{item.label}</span><span className="text-xs text-slate-400">{tracks.find((t: Track) => t.id === item.trackId)?.title}</span></button></li>)}</ol> : <p className="mt-8 text-slate-400">Create the script sequence or add a sound to start a manual sequence. It never advances by itself: use the arrow keys or select a cue.</p>}</> }
function Player({ track, playing, toggle, time, seek, jump, effects, update }: any) { return <section className="glass fixed bottom-4 left-1/2 z-10 w-[min(94vw,1050px)] -translate-x-1/2 rounded-3xl p-4 shadow-2xl"><div className="flex flex-wrap items-center gap-4"><div className="min-w-36 flex-1"><p className="text-sm font-black capitalize">{track.title}</p><p className="text-xs text-slate-400">{format(time)} • live effects enabled</p></div><button className="icon" onClick={() => jump(-5)}><Rewind size={19}/></button><button className="play" onClick={toggle}>{playing ? <Pause fill="currentColor"/> : <Play fill="currentColor"/>}</button><button className="icon" onClick={() => jump(5)}><FastForward size={19}/></button><input className="w-36 accent-cyan-300" type="range" min="0" max={track.duration || 300} value={time} onChange={e => seek(Number(e.target.value))}/><div className="hidden min-w-64 gap-3 md:grid"><EffectControls compact effects={effects} update={update}/></div></div></section> }
function EffectControls({ effects, update, compact = false }: { effects: Effects; update: (fx: Effects) => void; compact?: boolean }) { const shown = compact ? controls.slice(0, 4) : controls; return <div className={compact ? "grid grid-cols-2 gap-x-3 gap-y-1" : "mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"}>{shown.map(control => <label key={control.key} className="block"><span className="mb-1 flex justify-between text-xs font-bold text-slate-300">{control.label}<b className="text-cyan-300">{Number(effects[control.key]).toFixed(control.step < .1 ? 2 : 1)}{control.unit}</b></span><input className="w-full accent-cyan-300" type="range" min={control.min} max={control.max} step={control.step} value={Number(effects[control.key])} onChange={e => update({ ...effects, [control.key]: Number(e.target.value) })}/></label>)}</div> }
function WebglBackdrop() { useEffect(() => { const canvas = document.querySelector("canvas") as HTMLCanvasElement; const gl = canvas?.getContext("webgl"); if (!gl) return; const render = () => { canvas.width = innerWidth; canvas.height = innerHeight; gl.viewport(0, 0, canvas.width, canvas.height); gl.clearColor(.02, .05, .1, 1); gl.clear(gl.COLOR_BUFFER_BIT); requestAnimationFrame(render); }; render(); }, []); return <canvas aria-hidden className="fixed inset-0 -z-10 h-full w-full"/>; }
